# Generated by Django 2.2.4 on 2019-12-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
