# Generated by Django 2.2.4 on 2019-12-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_description',
        ),
    ]
